name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Lint
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...
      - name: Test
        run: go test ./...
